### ISSUE TITLE
Issue & Request

### ISSUE THREAD

**Issue by bilalinamdar** [spoonboy-io/custom-tab-plugin#1]
Hi,
First of all thanks for the plugin i tried it and it worked fine. Also it is well explained so a novice can also follow. Thanks for that too.

**[ISSUE]** The issue first with the plugin was if we use different mysql database (eg remote) it throws gasket error for all instance pages. The external database i used for testing freemysqlhosting.net. You have made the morpheus database name mentioned in some places of the code that is also conflicting while using remote database. The remote db name should be morpheus too ! but again that was another error. To resolve have to follow the readme and create table in the official mysql database 'morpheus' which is a little risky. Again it is not mentioned but a readonly user is also created to access the table. In your case you used deluser.

![gasket error](https://github.com/spoonboy-io/custom-tab-plugin/assets/7912006/886c49a5-96a0-47a2-a118-c6d99dfa319a)
![db name error](https://github.com/spoonboy-io/custom-tab-plugin/assets/7912006/555134cb-fdad-46b8-99c4-6b71bcfbba55)

**[REQUEST]** Now coming to my main motive.
Can you please create something as we can add our page inside of this custom-tab section ? 

1) Dump all variable send by morpheus to the custom-tab (on off switch) this is for diagnostic and improvement purpose
2) IFRAME / website page inplace of the current content. Changeable link.

Can this be done ? it will be very useful for handling other requests of the users.

I should have asked it in request section but i don't know where exactly should i post this.

**Comment by olliephillips** [comment]
Hi. Yes that's correct. The primary reason for the additional DB connection was to facilitate writes, as that isn't possible via Morpheus Plugin helper methods at this time, and the read methods used in the plugin are report helpers which will only read from the Morpheus database.

So, as it written in the example code the additional connection must also target the Morpheus database, but the permissions can be applied on the user in MySQL so it only has grants to write to the specific table. 

Some work would be required by the user to use a different database.

Re the suggestions/requests certainly both of those plugins would be use cases for custom tab plugin provider.
