### ISSUE TITLE
After upgrade not working 6.0.6

### ISSUE THREAD

**Issue by bilalinamdar** [spoonboy-io/custom-tab-plugin#2]
![chrome_IB7JkrTG7p](https://github.com/spoonboy-io/custom-tab-plugin/assets/7912006/e0c72ced-b4ba-43fe-a771-d1a1ca540254)
Hi,

Yesterday i did a upgrade of morpheus and it disappeared.
When added back i am getting this error

[grails.rabbit.exchange.pluginReloadEvent.container-3] Error Initializing Plugin Objects for Plugin: Managed Service Instance Tab ... Unloading Plugin....null java.lang.NullPointerException: null

in the plugin ui there is a minus sign which says file not found.

even after adding the file to /var/opt/morpheus/morpheus-local/plugins-embedded/ and changing the ownership it is not working.

seems broken :( was fine with 6.0.4
Also tried to change the plugin 0.14.4 which is recommended for 6.0.6 still same issue.

**Comment by bilalinamdar** [comment]
ping pong

**Comment by olliephillips** [comment]
Hi @bilalinamdar. Just to clarify, the code in this repo is not supported. It is intended as an enabler for those trying to develop their own similar plugins. It was tested against a Morpheus version and was seen to be working, but we are still pre-version 1 of the plugin framework and breaking changes are possible. I will close this for now.
